name: Java CI with Maven Testing

on:
     
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build using pom xml
      run: > 
        mvn clean test

#     Report Generation
    - name: archive report artifact
      uses: actions/upload-artifact@v3
      with:
        name: sparkHTML
        path: ./reports/*.html

